import Roulette from './Roulette'

const App = () => {
  var options = [
    { name: "Una película de Disney", tags: ["película"] },
    { name: "Una marca de autos", tags: ["marca"] },
    { name: "Un deporte olímpico", tags: ["deporte"] },
    { name: "Un actor o actriz ganador de un Oscar", tags: ["cine"] },
    { name: "Un animal en peligro de extinción", tags: ["naturaleza"] },
    { name: "Una serie de televisión famosa", tags: ["televisión"] },
    { name: "Una marca de ropa deportiva", tags: ["moda"] },
    { name: "Un pintor famoso", tags: ["arte"] },
    { name: "Un líder histórico", tags: ["historia"] },
    { name: "Una red social", tags: ["tecnología"] },
    { name: "Un plato típico italiano", tags: ["comida"] },
    { name: "Un libro clásico", tags: ["literatura"] },
    { name: "Una serie animada para niños", tags: ["televisión"] },
    { name: "Un superhéroe de Marvel", tags: ["cómic"] },
    { name: "Una ciudad europea", tags: ["geografía"] },
    { name: "Un postre", tags: ["comida"] },
    { name: "Un equipo de fútbol europeo", tags: ["deporte"] },
    { name: "Un director de cine", tags: ["cine"] },
    { name: "Un dios de mitología griega", tags: ["historia"] },
    { name: "Una serie de ciencia ficción", tags: ["televisión"] },
    { name: "Una marca de zapatillas", tags: ["moda"] },
    { name: "Una bebida no alcohólica", tags: ["bebida"] },
    { name: "Un estilo artístico", tags: ["arte"] },
    { name: "Una serie de dibujos animados clásica", tags: ["televisión"] },
    { name: "Un presidente de Estados Unidos", tags: ["historia"] },
    { name: "Una novela de ciencia ficción", tags: ["literatura"] },
    { name: "Un monumento famoso", tags: ["historia"] },
    { name: "Un plato típico de la cocina asiática", tags: ["comida"] },
    { name: "Un actor de comedia", tags: ["cine"] },
    { name: "Un animal marino", tags: ["naturaleza"] },
    { name: "Un personaje de la mitología nórdica", tags: ["historia"] },
    { name: "Un juego de mesa clásico", tags: ["juego"] },
    { name: "Una serie de televisión de crimen/detectives", tags: ["televisión"] },
    { name: "Un tipo de danza latinoamericana", tags: ["arte"] },
    { name: "Una ciudad ficticia", tags: ["Ficcion"] },
    { name: "Un supervillano de Marvel", tags: ["cómic"] },
    { name: "Un equipo de superhéroes", tags: ["cómic"] },
    { name: "Un mutante de X-Men", tags: ["cómic"] },
    { name: "Una tira cómica", tags: ["cómic"] },
    { name: "Un villano de Spider-Man", tags: ["cómic"] },
    { name: "Un pelicula basada en un comic que no sea de DC o Marvel", tags: ["cómic"] },
    { name: "Un objeto icónico de un cómic", tags: ["cómic"] },
    { name: "Un evento crossover de cómics", tags: ["cómic"] },
    { name: "Un supervillano de Batman", tags: ["cómic"] },
    { name: "Un videojuego de estrategia en tiempo real (RTS)", tags: ["videojuego"] },
    { name: "Un videojuego de mundo abierto", tags: ["videojuego"] },
    { name: "Un videojuego de arcade", tags: ["videojuego"] },
    { name: "Un videojuego de terror", tags: ["videojuego"] },
    { name: "Un título de la saga Final Fantasy", tags: ["videojuego"] },
    { name: "Un juego de ciencia ficción", tags: ["videojuego"] },
    { name: "Un videojuego basado en una película o serie", tags: ["videojuego"] },
    { name: "Un personaje de un videojuego de lucha", tags: ["videojuego"] },
    { name: "Una provincia argentina", tags: ["geografía"] },
    { name: "Una comida típica argentina", tags: ["comida"] },
    { name: "Una película argentina", tags: ["cine"] },
    { name: "Un lugar turístico en Argentina", tags: ["geografía"] },
    { name: "Un feriado", tags: ["cultura"] },
    { name: "Un equipo de fútbol argentino", tags: ["deporte"] },
    { name: "Un manga de género shonen", tags: ["manga"] },
    { name: "Un robot gigante", tags: ["manga"] },
    { name: "Una raza ficticia", tags: ["ficcion"] },
    { name: "Un arma legendaria", tags: ["ficcion"] },
    { name: "Un planeta ficticio de un universo de ciencia ficción", tags: ["ficcion"] },
    { name: "Una nave espacial famosa", tags: ["ficcion"] },
    { name: "Un artefacto mágico de la literatura fantástica", tags: ["ficcion"] },
    { name: "Una civilización alienígena ficticia", tags: ["ficcion"] },
    { name: "Una obra de ficción distópica", tags: ["ficcion"] },
    { name: "Un personaje androide de ficcion", tags: ["ficcion"] },
    { name: "Un personaje con poderes psíquicos", tags: ["ficcion"] },
    { name: "Un viajero en el tiempo", tags: ["ficcion"] },
    { name: "Un animal mágico", tags: ["ficcion"] },
    { name: "Un evento apocalíptico ficticio", tags: ["ficcion"] },
    { name: "Un descubrimiento científico importante", tags: ["ciencia"] },
    { name: "Un filósofo famoso", tags: ["filosofía"] },
    { name: "Un movimiento artístico", tags: ["arte"] },
    { name: "Una obra de teatro clásica", tags: ["teatro"] },
    { name: "Un músico clásico", tags: ["música"] },
    { name: "Un tipo de queso", tags: ["comida"] },
    { name: "Una fruta tropical", tags: ["comida"] },
    { name: "Una forma de decir mate sin decir mate", tags: ["comida"] },
    { name: "Un juego de mesa que use dados", tags: ["comida"] },
    { name: "Un juego de mesa que no use dados", tags: ["comida"] },
    { name: "Un clásico del cine en blanco y negro", tags: ["cine"] },
    { name: "Una película de ciencia ficción de los años 80", tags: ["cine"] },
    { name: "Una película de terror", tags: ["cine"] },
    { name: "Una película basada en hechos reales", tags: ["cine"] },
    { name: "Una película animada de Pixar", tags: ["cine"] },
    { name: "Una película de Quentin Tarantino", tags: ["cine"] },
    { name: "Un musical", tags: ["cine"] },
    { name: "Una película de animación japonesa (anime)", tags: ["cine"] },
    { name: "Una película de comedia romántica", tags: ["cine"] },
    { name: "Una de las 7 maravillas del mundo antiguo", tags: ["historia"] },
    { name: "Un hueso del cuerpo humano", tags: ["anatomía"] },
    { name: "Una cadena montañosa", tags: ["geografía"] },
    { name: "Un continente", tags: ["geografía"] },
    { name: "Una persona que este jugando este juego actualmente", tags: ["general"] },
    { name: "Un animal prehistorico", tags: ["general"] },
    { name: "Un elemento químico de la tabla periódica", tags: ["ciencia"] },
    { name: "Una obra de teatro de Shakespeare", tags: ["teatro"] },
    { name: "Un género musical", tags: ["música"] },
    { name: "Un intérprete de jazz legendario", tags: ["música"] },

    

  
  ];
  return Roulette(options.map(o => o.name).sort(() => (Math.random() > .5) ? 1 : -1));
};

export default App;